using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Database.Link {
    public sealed class LinkConfiguration : IEntityTypeConfiguration<LinkModel> {
        public void Configure(EntityTypeBuilder<LinkModel> builder) {
            // Map LinkModel to Links table
            builder.ToTable("Links");
            
            // Say that id is generated key
            builder.HasKey(l => l.Id);
            builder.Property(l => l.Id).ValueGeneratedOnAdd().UseIdentityAlwaysColumn();
            
            // Say that CreatedAt is autogenerated 
            // readonly field
            builder
                .Property(l => l.CreatedAt)
                .HasDefaultValueSql("now()")
                .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);
            
            // Say that Link have many-to-one relation ship with Users
            builder
                .HasOne(l => l.User)
                .WithMany(u => u.Links)
                .HasForeignKey(l => l.UserId);
        }
    }
}